In [1]:
import numpy as np

In [5]:
a= np.array([2,3,4])
a

array([2, 3, 4])

In [7]:
c=np.array([2,3,4,5,6,2]).reshape(2,3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In [12]:
e=np.array([1,2,3,4,5,6])
print("sum:",e.sum()) #sum the array
print(e.min()) #find the minimum value in an array
print(e.max()) #find the maximum value in an array
print(e.mean()) #find the aritmatic of an array

sum: 21
1
6
3.5


In [13]:
np.zeros(5) #creates an arrayof zeros with 5 element

array([0., 0., 0., 0., 0.])

In [14]:
np.linspace(0,6,10) #create an array of values  from 0 through 6 in 10even spaces

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [15]:
np.random.rand(3) #three random values between0 and 1

array([0.4477781 , 0.02800062, 0.91662222])

In [16]:
np.random.randint(1,100) #a random integer between 1 and 100

32

In [17]:
np.arange(25) #like the "range" function we learned earlier, this is gives you a rnge of integer between 1-25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])